# Generated by Django 4.2.11 on 2025-03-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='booking_status',
            field=models.CharField(default='Available', max_length=50),
            preserve_default=False,
        ),
    ]
