# Generated by Django 4.2.11 on 2025-03-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_seat_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='seat_status',
            field=models.CharField(choices=[('one', 'Available'), ('two', 'Booked')], default='Available', max_length=20),
            preserve_default=False,
        ),
    ]
