# Generated by Django 4.2.11 on 2025-03-04 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_seat_seat_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='booking_status',
        ),
    ]
